AllCops:
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Gemspec/AddRuntimeDependency:
  Enabled: true

Lint/AmbiguousAssignment:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
